/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    CircRNA_detail: typeof import('./components/circRNA_detail/circRNA_detail.vue')['default']
    CircRNA_ID_form: typeof import('./components/circRNA_search/circRNA_ID_form.vue')['default']
    CircRNA_identification_subtable: typeof import('./components/circRNA_detail/circRNA_identification_subtable.vue')['default']
    CircRNA_isoforms_subtable: typeof import('./components/circRNA_detail/circRNA_isoforms_subtable.vue')['default']
    CircRNA_search: typeof import('./components/circRNA_search/circRNA_search.vue')['default']
    CircRNA_search_result: typeof import('./components/circRNA_search_result/circRNA_search_result.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    General_function_subtitle: typeof import('./components/general_function_subtitle.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IDType_selector: typeof import('./components/circRNA_search/IDType_selector.vue')['default']
    Isoform_mirna_site_detail: typeof import('./components/circRNA_detail/isoform_mirna_site_detail.vue')['default']
    Isoform_mirna_sites: typeof import('./components/circRNA_detail/isoform_mirna_sites.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCondition_circRNA: typeof import('./components/circRNA_search/SearchCondition_circRNA.vue')['default']
  }
}
