/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    Blast_root: typeof import('./components/blast_root/blast_root.vue')['default']
    CircRNA_detail: typeof import('./components/circRNA_detail/circRNA_detail.vue')['default']
    CircRNA_ID_form: typeof import('./components/circRNA_search/circRNA_ID_form.vue')['default']
    CircRNA_identification_subtable: typeof import('./components/circRNA_detail/circRNA_identification_subtable.vue')['default']
    CircRNA_isoforms_subtable: typeof import('./components/circRNA_detail/circRNA_isoforms_subtable.vue')['default']
    CircRNA_search: typeof import('./components/circRNA_search/circRNA_search.vue')['default']
    CircRNA_search_result: typeof import('./components/circRNA_search_result/circRNA_search_result.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLoading: typeof import('element-plus/es')['ElLoading']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    General_function_subtitle: typeof import('./components/general_function_subtitle.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home_page: typeof import('./components/home_page/home_page.vue')['default']
    HomePage: typeof import('./components/homePage/homePage.vue')['default']
    IRES_detail: typeof import('./components/IRES_detail/IRES_detail.vue')['default']
    Isoform_mirna_sites: typeof import('./components/circRNA_detail/isoform_mirna_sites.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    M6A_detail: typeof import('./components/m6A_detail/m6A_detail.vue')['default']
    mirna_detail: typeof import('./components/mirna_detail/mirna_detail.vue')['default']
    Mirna_detail: typeof import('./components/mirna_detail/mirna_detail.vue')['default']
    ORF_detail: typeof import('./components/ORF_detail/ORF_detail.vue')['default']
    RBP_detail: typeof import('./components/RBP_detail/RBP_detail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCondition_circRNA: typeof import('./components/circRNA_search/SearchCondition_circRNA.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
